name: Deploy to S3 and invalidate CloudFront

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Github Repository 파일 불러오기
        uses: actions/checkout@v4

      - name: Repository 파일 출력하기
        run: ls

      - name: 의존성 설치
        run: npm i
        working-directory: assignment-bucketcreate-vite

      - name: 빌드하기
        run: npm run build
        working-directory: assignment-bucketcreate-vite

      - name: Debugging
        run: |
          ls
          echo "--------------"
          cd dist
          ls
